[auth]
redirect_uri = "http://localhost:8501"

[auth.google]
client_id = "GOOGLE_CLIENT_ID"
client_secret = "GOOGLE_CLIENT_SECRET"

[auth.github]
client_id = "GITHUB_CLIENT_ID"
client_secret = "GITHUB_CLIENT_SECRET"